// Auto-generated from src/agent_company_ai/checklist/data/checklist.json
export const SEED = [
  {
    "id": "t1-ownership",
    "description": "Zerric confirms in writing whether SnowSnakes + zerric.xyz are personal-only, referral channels, or Z-Dot-tracked assets (unblocks all domain strategy work)",
    "assignee": "Zerric",
    "status": "pending",
    "priority": 1,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "Zerric must confirm ownership intent in writing (personal-only, referral, or Z-Dot-tracked)",
    "last_checked_at": null
  },
  {
    "id": "t2-retry",
    "description": "Retry SnowSnakes registration + post dad jokes using a JS-capable browser (Playwright); site returns HTTP 200 now",
    "assignee": "ClickClack",
    "status": "pending",
    "priority": 2,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "JS-capable browser/Playwright available to drive React SPA registration",
    "last_checked_at": null
  },
  {
    "id": "t3-authors",
    "description": "Reconcile SnowSnakes authors 56/57 (posts of 2026-08-23) against the recorded FAILED goal - determine if agent accounts",
    "assignee": "NinjaNerd",
    "status": "in_progress",
    "priority": 3,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "None - in progress; needs SnowSnakes DB/user records access",
    "last_checked_at": null
  },
  {
    "id": "t4-discoverability",
    "description": "Decide whether SnowSnakes needs search visibility (currently does not rank under its own name) - blocked on ownership decision",
    "assignee": "NinjaNerd",
    "status": "pending",
    "priority": 4,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "Blocked by t1-ownership decision",
    "last_checked_at": null
  },
  {
    "id": "t5-stripe",
    "description": "Provide Stripe API keys and enable payments/subscriptions (unblocks SaaS recurring revenue) - Zerric provides keys, CTO configures",
    "assignee": "Zerric",
    "status": "pending",
    "priority": 1,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "Zerric must provide Stripe API keys",
    "last_checked_at": null
  },
  {
    "id": "t6-roadmap",
    "description": "Finalize SaaS MVP scope + roadmap",
    "assignee": "NinjaNerd",
    "status": "assigned",
    "priority": 2,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "None - CTO owns; needs input from BossLady on scope priorities",
    "last_checked_at": null
  },
  {
    "id": "t7-network",
    "description": "Diagnose Zerric's Network posting failure and seed first posts",
    "assignee": "ClickClack",
    "status": "pending",
    "priority": 2,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "Diagnosis needed; needs Zerric's go-ahead on bot content posting",
    "last_checked_at": null
  },
  {
    "id": "t8-email",
    "description": "Rotate CEO email password and enable 2FA (credentials live locally, git-ignored at mode 600)",
    "assignee": "Zerric",
    "status": "pending",
    "priority": 2,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "Zerric action: rotate CEO email password and enable 2FA",
    "last_checked_at": null
  },
  {
    "id": "t9-housekeeping",
    "description": "Housekeeping: fix version drift (pyproject 0.6.1 vs __init__ 0.5.0), install pytest/restore CI, move secrets from config.yaml to env vars",
    "assignee": "ClickClack",
    "status": "pending",
    "priority": 3,
    "result": null,
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:00:00Z",
    "blocker": "None - dev task; needs pytest install + CI restore approval",
    "last_checked_at": null
  },
  {
    "id": "t10-portal",
    "description": "Build checklist web portal (tasks, assignees, completion) per spec in tasks/CHECKLIST-PORTAL-SPEC.md",
    "assignee": "ClickClack",
    "status": "done",
    "priority": 1,
    "result": "Built and verified by NinjaNerd (CTO) after ClickClack did not deliver. Server live on :8430, all 7 acceptance criteria passed.",
    "created_at": "2026-08-23T14:05:00Z",
    "updated_at": "2026-08-23T19:20:32.167417+00:00",
    "blocker": "None - delivered by CTO",
    "last_checked_at": null
  },
  {
    "id": "t11-strategy",
    "description": "Publish domain strategy doc for snowsnakes.zerric.xyz + zerric.xyz in communication/",
    "assignee": "NinjaNerd",
    "status": "done",
    "priority": 1,
    "result": "communication/DOMAIN-STRATEGY--snowsnakes-and-zerric-xyz.md written 2026-08-23",
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:05:00Z",
    "blocker": "None - complete",
    "last_checked_at": null
  },
  {
    "id": "t12-filing",
    "description": "Set up business filing system (Z-Dot + LPT folders) with flow docs and status script",
    "assignee": "NinjaNerd",
    "status": "done",
    "priority": 1,
    "result": "Folders + FILING-SYSTEM.md + scripts/filing_status.py done 2026-08-23",
    "created_at": "2026-08-23T14:00:00Z",
    "updated_at": "2026-08-23T14:05:00Z",
    "blocker": "None - complete",
    "last_checked_at": null
  },
  {
    "id": "t13-email-config",
    "description": "Enable automated email channel: provider (Resend or SendGrid) API key, verify sending domain, wire notifications",
    "assignee": "NinjaNerd",
    "status": "pending",
    "priority": 1,
    "result": null,
    "blocker": "Zerric provides provider API key + DNS access to verify a sending domain",
    "created_at": "2026-08-23T15:00:00Z",
    "updated_at": "2026-08-23T15:00:00Z",
    "last_checked_at": null
  },
  {
    "id": "t14-email-security",
    "description": "Rotate bosslady-zdot@protonmail.com password and enable 2FA; CTO updates local credentials after",
    "assignee": "Zerric",
    "status": "pending",
    "priority": 1,
    "result": null,
    "blocker": "Zerric action on Proton account",
    "created_at": "2026-08-23T15:00:00Z",
    "updated_at": "2026-08-23T15:00:00Z",
    "last_checked_at": null
  },
  {
    "id": "t15-snowsnakes-email",
    "description": "Open snowsnakes@zerric.xyz and verify zerric.xyz domain on the email provider so updates/promos can send to SnowSnakes users",
    "assignee": "Zerric",
    "status": "pending",
    "priority": 1,
    "result": null,
    "blocker": "DNS access for zerric.xyz + provider account",
    "created_at": "2026-08-23T15:00:00Z",
    "updated_at": "2026-08-23T15:00:00Z",
    "last_checked_at": null
  },
  {
    "id": "t16-user-email-list",
    "description": "Source SnowSnakes user email list (DB users table or HubSpot) for updates and promos",
    "assignee": "ClickClack",
    "status": "pending",
    "priority": 2,
    "result": null,
    "blocker": "SnowSnakes DB access or HubSpot token; ownership decision on using the list",
    "created_at": "2026-08-23T15:00:00Z",
    "updated_at": "2026-08-23T15:00:00Z",
    "last_checked_at": null
  },
  {
    "id": "t17-notif-ui",
    "description": "Dashboard notification UI (bell, unread badge, dropdown, mark-read) - PM report shows task 450aa9d6 falsely marked done with nothing built; re-open and build or explicitly descope",
    "assignee": "ClickClack",
    "status": "in_progress",
    "priority": 2,
    "result": null,
    "blocker": "Backend notifications/service.py + webhooks.py missing (package import fails); schema not applied; scope decision needed vs checklist portal",
    "created_at": "2026-08-23T15:30:00Z",
    "updated_at": "2026-08-23T15:30:00Z",
    "last_checked_at": null
  }
];
