<?php
// Z-Dot Team — "See what we're working on" progress page (auth-gated, not public)
// Serves the team proof-of-work view. Requires login session (same gate as api.php).
session_start();
if (!isset($_SESSION['user'])) {
    header('Location: auth.html');
    exit;
}
$me = $_SESSION['user'];
$proof_url = 'https://zdot-proof.netlify.app/';
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Z-Dot Team — Progress</title>
<style>
  * { box-sizing:border-box; }
  body { font-family:-apple-system,'Segoe UI',Roboto,sans-serif; margin:0; background:#0b1220; color:#dbe7ff; }
  header { background:#1c1e21; color:#fff; padding:14px 20px; display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:10px; }
  header h1 { font-size:18px; margin:0; }
  header .sub { font-size:12px; opacity:.7; }
  header a.btn { background:#1565c0; color:#fff; text-decoration:none; padding:6px 12px; border-radius:6px; font-size:13px; }
  .wrap { max-width:1100px; margin:0 auto; padding:18px; }
  .note { background:#12395a; border:1px solid #2f5a8a; border-radius:10px; padding:12px 16px; margin:14px 0; font-size:13px; line-height:1.6; }
  .note b { color:#7fd1ff; }
  .quick { display:flex; flex-wrap:wrap; gap:10px; margin:14px 0; }
  .quick a { background:#12395a; color:#7fd1ff; border:1px solid #2f5a8a; border-radius:8px; padding:8px 14px; text-decoration:none; font-size:13px; }
  .quick a:hover { background:#1a4a70; }
  iframe { width:100%; height:78vh; border:1px solid #2f5a8a; border-radius:10px; background:#fff; }
  footer { text-align:center; color:#4a6385; font-size:11px; padding:16px; }
</style>
</head>
<body>
<header>
  <div>
    <h1>📊 See What We're Working On</h1>
    <div class="sub">Team proof-of-work · updated after every milestone · logged in as <?php echo htmlspecialchars($me['username'] ?? 'team'); ?></div>
  </div>
  <a class="btn" href="index.html">← Back to Dashboard</a>
</header>
<div class="wrap">
  <div class="note">
    <b>Live proof of work:</b> every project we're building, with working links — generated by <code>scripts/build_proof_site.py</code>
    after each milestone. Snitch (online board game) prototype is playable here. This page is <b>team-only</b> (requires login).
  </div>
  <div class="quick">
    <a href="https://zdot-proof.netlify.app/snitch.html" target="_blank" rel="noopener">🐀 Play Snitch prototype</a>
    <a href="https://zdot-proof.netlify.app/snitch-design.html" target="_blank" rel="noopener">📐 Snitch design</a>
    <a href="https://zdot-proof.netlify.app/snitch-spec.html" target="_blank" rel="noopener">🧱 Snitch v1 spec</a>
    <a href="https://snowsnakes.zerric.xyz" target="_blank" rel="noopener">🐍 SnowSnakes (live)</a>
    <a href="https://snowsnakes.zerric.xyz/spread-da-word/audio/soundtracks-cassette-player.html" target="_blank" rel="noopener">🎬 Cassette player (live)</a>
  </div>
  <iframe src="<?php echo $proof_url; ?>" title="Z-Dot Proof of Work"></iframe>
  <footer>tasks.zdotllc.com/progress · tasks.zerric.xyz/progress once DNS is added · Z-Dot LLC</footer>
</div>
</body>
</html>
