<?php
// Z-Dot Team - private proof-of-work page (requires login like api.php)
session_start();
if (!isset($_SESSION['user'])) {
    header('Location: auth.html');
    exit;
}
$me = $_SESSION['user'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Z-Dot Team — Progress (private)</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif; background:#0b1220; color:#dbe7ff; line-height:1.6; }
  .wrap { max-width:1000px; margin:0 auto; padding:28px 18px 60px; }
  header { text-align:center; padding:30px 0 8px; }
  header h1 { font-size:2rem; letter-spacing:1px; color:#fff; }
  header .tag { color:#7fd1ff; font-size:.95rem; letter-spacing:3px; margin-top:6px; }
  .updated { display:inline-block; margin-top:12px; background:#12395a; color:#9fd8ff; border:1px solid #2f5a8a; border-radius:20px; padding:5px 16px; font-size:.8rem; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(300px,1fr)); gap:16px; margin-top:26px; }
  .card { background:#101d33; border:1px solid #1f3a5f; border-radius:14px; padding:18px; }
  .card-head { display:flex; align-items:center; gap:10px; }
  .card-head .ic { font-size:1.6rem; }
  .card h2 { font-size:1.05rem; color:#fff; }
  .blurb { margin:8px 0 12px; color:#a9c2e5; font-size:.92rem; }
  .links { display:flex; flex-wrap:wrap; gap:8px; margin-bottom:12px; }
  .lnk { background:#12395a; color:#7fd1ff; border:1px solid #2f5a8a; border-radius:8px; padding:5px 10px; font-size:.78rem; text-decoration:none; }
  .lnk:hover { background:#1a4a70; }
  .meta { color:#6f8db0; font-size:.78rem; border-top:1px dashed #1f3a5f; padding-top:8px; }
  h3.section { margin-top:34px; color:#7fd1ff; letter-spacing:2px; font-size:.95rem; border-bottom:1px solid #1f3a5f; padding-bottom:8px; }
  .live { display:flex; flex-wrap:wrap; gap:10px; margin-top:14px; }
  .live a { background:#0e2a1e; color:#7ee2a8; border:1px solid #1f5a3f; border-radius:8px; padding:7px 12px; font-size:.85rem; text-decoration:none; }
  table { width:100%; border-collapse:collapse; margin-top:14px; font-size:.8rem; }
  td { padding:6px 8px; border-bottom:1px solid #14263f; color:#a9c2e5; }
  td.hash { color:#7fd1ff; font-family:monospace; white-space:nowrap; }
  .personas { display:flex; flex-wrap:wrap; gap:8px; margin-top:14px; }
  .persona { background:#101d33; border:1px solid #1f3a5f; border-radius:8px; padding:5px 10px; font-size:.82rem; }
  .doodles { display:grid; grid-template-columns:repeat(auto-fill,minmax(130px,1fr)); gap:10px; margin-top:14px; }
  .doodle { background:#101d33; border:1px solid #1f3a5f; border-radius:10px; padding:8px; text-align:center; }
  .doodle img { width:100%; height:auto; border-radius:6px; background:#0a1526; }
  .doodle p { font-size:.7rem; color:#a9c2e5; margin-top:6px; }
  .blockers li { margin:6px 0 6px 18px; color:#ffb3a0; }
  footer { margin-top:40px; text-align:center; color:#4a6385; font-size:.75rem; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <h1>Z-DOT TEAM · PROOF OF WORK</h1>
    <div class="tag">TANGIBLE PROGRESS · LIVE LINKS · VERIFIED</div>
    <div><span class="updated">Last updated 2026-08-25 00:00 UTC · regenerated by scripts/build_proof_site.py</span></div>
  </header>

  <h3 class="section">🟢 LIVE SYSTEMS</h3>
  <div class="live">
    <a href="https://snowsnakes.zerric.xyz" target="_blank" rel="noopener">✓ snowsnakes.zerric.xyz</a>
    <a href="https://tasks.zdotllc.com" target="_blank" rel="noopener">✓ tasks.zdotllc.com</a>
    <a href="https://spread-da-word.netlify.app/" target="_blank" rel="noopener">✓ spread-da-word.netlify.app</a>
    <a href="https://snowsnakes.zerric.xyz/spread-da-word/audio/soundtracks-cassette-player.html" target="_blank" rel="noopener">✓ Cassette player</a>
    <a href="snitch.html" target="_blank" rel="noopener">✓ Snitch prototype</a>
  </div>

  <h3 class="section">📦 PROJECTS</h3>
  <div class="grid">
<div class="card">
      <div class="card-head"><span class="ic">🎬</span><h2>Spread Da Word — Animated Series</h2></div>
      <p class="blurb">Cassette player with 8 switchable tapes (each its own label/colors/download), live on SnowSnakes.</p>
      <div class="links"><a class="lnk" href="https://snowsnakes.zerric.xyz/spread-da-word/audio/soundtracks-cassette-player.html" target="_blank" rel="noopener">Cassette player (live) ↗</a><a class="lnk" href="https://snowsnakes.zerric.xyz" target="_blank" rel="noopener">SDW official channel (live) ↗</a><a class="lnk" href="https://snowsnakes.zerric.xyz/spread-da-word/audio/soundtracks-cassette-player.html" target="_blank" rel="noopener">5 new soundtracks rendered ↗</a><a class="lnk" href="https://spread-da-word.netlify.app/" target="_blank" rel="noopener">Hub + legal pages (Netlify) ↗</a></div>
      <p class="meta">Series world: Vin Negar, Que, Hood vs Fridge, cassettes, episodes placeholder.</p>
    </div>
<div class="card">
      <div class="card-head"><span class="ic">🐀</span><h2>Snitch — Online Board Game</h2></div>
      <p class="blurb">Rats racing the snake board. 4-player cap, sign-in = lead capture, 3 modes (solo vs bots / invite / quick-play).</p>
      <div class="links"><a class="lnk" href="./snitch.html" target="_blank" rel="noopener">Play the prototype ↗</a><a class="lnk" href="./snitch-design.html" target="_blank" rel="noopener">Design (canon) ↗</a><a class="lnk" href="./snitch-spec.html" target="_blank" rel="noopener">v1 Build spec ↗</a></div>
      <p class="meta">Working prototype in repo. Online P2P layer + HubSpot lead capture = next build.</p>
    </div>
<div class="card">
      <div class="card-head"><span class="ic">📣</span><h2>Outreach Sprint</h2></div>
      <p class="blurb">Prospect → CRM loop. HubSpot sync tool built and run against 29 Louisville prospect leads.</p>
      <div class="links"><a class="lnk" href="https://github.com/zaxbatch/agent-company-ai" target="_blank" rel="noopener">Sync tool ↗</a><a class="lnk" href="https://app.hubspot.com/" target="_blank" rel="noopener">HubSpot CRM ↗</a></div>
      <p class="meta">28 created, 1 updated (last run 2026-08-24 09:22). Next: email outreach (blocked on provider key).</p>
    </div>
<div class="card">
      <div class="card-head"><span class="ic">🐍</span><h2>SnowSnakes — Community</h2></div>
      <p class="blurb">Live community site. Content runs as 8 realistic personas (no more team-handle bots).</p>
      <div class="links"><a class="lnk" href="https://snowsnakes.zerric.xyz" target="_blank" rel="noopener">SnowSnakes (live) ↗</a><a class="lnk" href="#snowsnakes" target="_blank" rel="noopener">Personas ↗</a></div>
      <p class="meta">8 realistic personas registered (ids 72-79). Jokes/games posting paused per house-cleaning; resumes on go.</p>
    </div>
<div class="card">
      <div class="card-head"><span class="ic">🖥️</span><h2>Platform & Infra</h2></div>
      <p class="blurb">Team portal, legal pages, git history, email/SMS channels — the operating backbone.</p>
      <div class="links"><a class="lnk" href="https://tasks.zdotllc.com" target="_blank" rel="noopener">Team portal (live) ↗</a><a class="lnk" href="https://spread-da-word.netlify.app/privacy.html" target="_blank" rel="noopener">Legal pages (Netlify) ↗</a><a class="lnk" href="https://github.com/zaxbatch/agent-company-ai" target="_blank" rel="noopener">Repo (private) ↗</a></div>
      <p class="meta">Dashboard + checklist portal live. State snapshots every 30 min.</p>
    </div>
  </div>

  <h3 class="section">🐀 SNOWSNAKES PERSONAS (real-user look)</h3>
  <div class="personas"><span class="persona">🍳 sam_rivera</span><span class="persona">🎧 nia_brooks</span><span class="persona">🎮 leo_park</span><span class="persona">🐀 rae_dunn</span><span class="persona">🌮 kai_torres</span><span class="persona">🎸 elle_marsh</span><span class="persona">🏀 max_fields</span><span class="persona">📚 ivy_chen</span></div>

  <h3 class="section">🎨 DOODLES FOR APPROVAL (latest batch)</h3>
  <div class="doodles"><div class="doodle"><img src="doodle-01-aji-hot-doodle.svg" alt="Aji Hot Doodle" loading="lazy"><p>Aji Hot Doodle</p></div><div class="doodle"><img src="doodle-02-crisp-ranch-doodle.svg" alt="Crisp Ranch Doodle" loading="lazy"><p>Crisp Ranch Doodle</p></div><div class="doodle"><img src="doodle-03-doodle-01-vin-que-parking-lot.svg" alt="Doodle 01 Vin Que Parking Lot" loading="lazy"><p>Doodle 01 Vin Que Parking Lot</p></div><div class="doodle"><img src="doodle-04-doodle-02-red-yellow-rivalry.svg" alt="Doodle 02 Red Yellow Rivalry" loading="lazy"><p>Doodle 02 Red Yellow Rivalry</p></div><div class="doodle"><img src="doodle-05-doodle-03-snow-snake-watching.svg" alt="Doodle 03 Snow Snake Watching" loading="lazy"><p>Doodle 03 Snow Snake Watching</p></div><div class="doodle"><img src="doodle-06-doodle-04-mayo-whip-twins.svg" alt="Doodle 04 Mayo Whip Twins" loading="lazy"><p>Doodle 04 Mayo Whip Twins</p></div><div class="doodle"><img src="doodle-07-doodle-05-aji-heat.svg" alt="Doodle 05 Aji Heat" loading="lazy"><p>Doodle 05 Aji Heat</p></div><div class="doodle"><img src="doodle-08-doodle-06-cookout.svg" alt="Doodle 06 Cookout" loading="lazy"><p>Doodle 06 Cookout</p></div><div class="doodle"><img src="doodle-09-mayo-white-doodle.svg" alt="Mayo White Doodle" loading="lazy"><p>Mayo White Doodle</p></div><div class="doodle"><img src="doodle-10-que-cookout-doodle.svg" alt="Que Cookout Doodle" loading="lazy"><p>Que Cookout Doodle</p></div><div class="doodle"><img src="doodle-11-red-ketchup-doodle.svg" alt="Red Ketchup Doodle" loading="lazy"><p>Red Ketchup Doodle</p></div><div class="doodle"><img src="doodle-12-snow-snake-doodle.svg" alt="Snow Snake Doodle" loading="lazy"><p>Snow Snake Doodle</p></div><div class="doodle"><img src="doodle-13-soy-proverb-doodle.svg" alt="Soy Proverb Doodle" loading="lazy"><p>Soy Proverb Doodle</p></div><div class="doodle"><img src="doodle-14-vin-negar-doodle.svg" alt="Vin Negar Doodle" loading="lazy"><p>Vin Negar Doodle</p></div><div class="doodle"><img src="doodle-15-whip-miracle-doodle.svg" alt="Whip Miracle Doodle" loading="lazy"><p>Whip Miracle Doodle</p></div><div class="doodle"><img src="doodle-16-yellow-mustard-doodle.svg" alt="Yellow Mustard Doodle" loading="lazy"><p>Yellow Mustard Doodle</p></div></div>

  <h3 class="section">🧾 RECENT COMMITS</h3>
  <table>
<tr><td class="hash">e70262e</td><td>state snapshot 20260824-233002</td></tr><tr><td class="hash">cf32bba</td><td>snow beats: download-loop feature (offline WAV render) — live as game 98</td></tr><tr><td class="hash">8dc308b</td><td>snow beats: ship loop-download mod as game 97 on snowsnakes; doodles for approval; promo-games policy</td></tr><tr><td class="hash">cd3dc0d</td><td>doodles: 5 SVG doodles for approval (Vin, Que, Red, Snow Snake, Snitch rat)</td></tr><tr><td class="hash">69d365b</td><td>house cleaning #2: games-only snowsnakes, SDW 6-8 songs x2 per episode, progress page live at tasks.zdotllc.com/progress (auth-gated)</td></tr><tr><td class="hash">c5c2303</td><td>state snapshot 20260824-230002</td></tr><tr><td class="hash">051985b</td><td>house cleaning: stop content loops, team jokes minimal, proof-of-work site live (zdot-proof.netlify.app) + generator</td></tr><tr><td class="hash">fd21649</td><td>state snapshot 20260824-223002</td></tr><tr><td class="hash">f4a706d</td><td>state: snapshot 2026-08-24T22:05:01Z</td></tr><tr><td class="hash">2e359b3</td><td>state snapshot 20260824-220001</td></tr><tr><td class="hash">7ab8366</td><td>state snapshot 20260824-213001</td></tr><tr><td class="hash">4db7ca6</td><td>state snapshot 20260824-210001</td></tr><tr><td class="hash">f09ce7a</td><td>state snapshot 20260824-203001</td></tr><tr><td class="hash">1deeeb4</td><td>state: snapshot 2026-08-24T20:05:01Z</td></tr>
  </table>

  <h3 class="section">⛔ BLOCKERS / NEEDS</h3>
  <ul class="blockers">
    <li>Stripe API key (Zerric) — gates payments</li>
    <li>Email provider key (Resend) — gates outreach</li>
    <li>zerric.xyz FTP access — Snitch + SDW proper domains</li>
    <li>SnowSnakes admin — duplicate game cleanup</li>
  </ul>

  <footer>Z-Dot LLC · generated by scripts/build_proof_site.py · run after every progress to refresh this page</footer>
</div>
</body>
</html>

