#!/usr/bin/env python3
"""Build ONE categorized review page from SnowSnakes + our own R&D artifacts.

The SnowSnakes API only allows CORS from its own origin, so a static page cannot
fetch it in the browser. This bakes the data in at build time instead; re-run to
refresh. Output is a single self-contained HTML file.

    scripts/build_review_hub.py --outdir /tmp/hub
"""
from __future__ import annotations
import argparse, html, json, os, sys, urllib.error, urllib.request, datetime

API = "https://snowsnakes.zerric.xyz/api"
RAW = "https://raw.githubusercontent.com/zaxbatch/agent-company-ai/main"
BLOB = "https://github.com/zaxbatch/agent-company-ai/blob/main"


def get(path):
    try:
        with urllib.request.urlopen(API + path, timeout=25) as r:
            return json.loads(r.read().decode() or "[]")
    except (urllib.error.HTTPError, urllib.error.URLError, ValueError) as e:
        print(f"  ! {path}: {e}", file=sys.stderr)
        return []


def e(s):
    return html.escape(str(s or ""))


def card(title, meta, media, links):
    L = " · ".join(f'<a href="{e(u)}" target="_blank" rel="noopener">{e(t)}</a>' for t, u in links)
    return f'''<article class="card">
  <div class="thumb">{media}</div>
  <h3>{e(title)}</h3>
  <p class="meta">{e(meta)}</p>
  <p class="links">{L}</p>
</article>'''


def audio(url):
    return f'<audio controls preload="none" src="{e(url)}"></audio>'


def image(url):
    return f'<img loading="lazy" src="{e(url)}" alt="">'


def build():
    sections = []

    # ---- Music -------------------------------------------------------------
    songs = get("/songs")
    items = []
    for s in songs:
        title = s.get("title", "(untitled)")
        meta = f"{s.get('author_name') or 'unknown'} · {str(s.get('created_at',''))[:10]} · ♥ {s.get('likes',0)}"
        links = [("SnowSnakes", "https://snowsnakes.zerric.xyz/songs")]
        if s.get("audio_url"):
            links.append(("direct mp3", s["audio_url"]))
        items.append(card(title, meta, audio(s["audio_url"]) if s.get("audio_url") else "",
                          links))
    sections.append(("Music", "Tracks published on SnowSnakes.", items))

    # ---- R&D beats (our own) ----------------------------------------------
    beats = [
        dict(t="16-Bar Instrumental (128 BPM)", m="LMMS spec render · v2 baseline · 31.9s · Am-F-C-G",
             mp3=f"{RAW}/content/experiments/lmms/beat-16bar.mp3",
             links=[("LMMS project", f"{BLOB}/content/experiments/lmms/beat-16bar.mmp"),
                    ("JSON spec", f"{RAW}/content/experiments/lmms/beat-16bar.spec.json"),
                    ("WAV master", f"{RAW}/content/experiments/lmms/beat-16bar.wav")]),
        dict(t="8-Bar Demo (v1, superseded)", m="LMMS spec render · v1 · 16.9s · flat arrangement, kept for compare",
             mp3=f"{RAW}/content/experiments/lmms/beat-8bar.mp3",
             links=[("LMMS project", f"{BLOB}/content/experiments/lmms/beat-8bar.mmp"),
                    ("WAV master", f"{RAW}/content/experiments/lmms/beat-8bar.wav")]),
    ]
    items = [card(b["t"], b["m"], audio(b["mp3"]), b["links"]) for b in beats]
    sections.append(("R&D → Audio", "Generated by our own tooling, not published to any client site.",
                     items))

    # ---- Art ---------------------------------------------------------------
    doodles = get("/doodles")
    items = []
    for d in doodles:
        meta = f"{d.get('author_name') or 'unknown'} · {str(d.get('created_at',''))[:10]}"
        links = [("SnowSnakes", "https://snowsnakes.zerric.xyz/doodles")]
        if d.get("image_url"):
            links.append(("full size", d["image_url"]))
        items.append(card(d.get("title", "(untitled)"), meta,
                          image(d["image_url"]) if d.get("image_url") else "", links))
    sections.append(("Art", "Doodles from the SnowSnakes doodle maker.", items))

    # ---- Games -------------------------------------------------------------
    games = get("/games")
    items = []
    for g in games[-12:][::-1]:
        meta = f"game id {g.get('id')} · {str(g.get('created_at',''))[:10]} · ♥ {g.get('likes',0)}"
        links = [("play", f"https://snowsnakes.zerric.xyz/games")]
        items.append(card(g.get("title", "(untitled)"), meta, "", links))
    sections.append(("Games", "Playable on SnowSnakes.", items))

    nav = " ".join(f'<a href="#{e(n.lower().replace(" ", "-").replace("→","").replace("--","-").strip("-"))}">'
                   f'{e(n)}</a>' for n, _, _ in sections if n)

    body = []
    for name, blurb, items in sections:
        if not items:
            continue
        anchor = name.lower().replace(" ", "-").replace("→", "").replace("--", "-").strip("-")
        body.append(f'<section id="{e(anchor)}"><h2>{e(name)}</h2><p class="blurb">{e(blurb)}</p>'
                    f'<div class="grid">{"".join(items)}</div></section>')

    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = " · ".join(f"{name}: {len(items)}" for name, _, items in sections if items)

    return f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Z-Dot Review Hub</title>
<style>
:root{{--bg:#0b0e14;--panel:#141924;--line:#232b3a;--tx:#e7ecf3;--dim:#8e9bb0;--accent:#6db3f2}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--tx);
 font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}}
header{{padding:36px 28px 20px;border-bottom:1px solid var(--line)}}
h1{{margin:0 0 6px;font-size:30px;letter-spacing:-.02em}}
.sub{{color:var(--dim);margin:0}}
nav{{margin-top:16px;display:flex;gap:8px;flex-wrap:wrap}}
nav a{{color:var(--accent);text-decoration:none;border:1px solid var(--line);
 padding:5px 12px;border-radius:999px;font-size:14px}}
nav a:hover{{border-color:var(--accent)}}
main{{padding:8px 28px 60px;max-width:1200px;margin:0 auto}}
section{{padding:28px 0;border-bottom:1px solid var(--line)}}
section:last-child{{border:0}}
h2{{margin:0 0 4px;font-size:21px}}
.blurb{{color:var(--dim);margin:0 0 18px;font-size:14px}}
.grid{{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:16px}}
.card{{background:var(--panel);border:1px solid var(--line);border-radius:10px;
 padding:14px;display:flex;flex-direction:column;gap:8px}}
.thumb{{border-radius:6px;overflow:hidden;background:#0e121a;min-height:0}}
.thumb img{{display:block;width:100%;height:auto}}
.thumb audio{{width:100%}}
h3{{margin:0;font-size:15px}}
.meta{{margin:0;color:var(--dim);font-size:12.5px}}
.links{{margin:auto 0 0;font-size:13px}}
.links a{{color:var(--accent);text-decoration:none}}
.links a:hover{{text-decoration:underline}}
footer{{padding:22px 28px 40px;color:var(--dim);font-size:12.5px;border-top:1px solid var(--line)}}
</style></head>
<body>
<header>
  <h1>Z-Dot Review Hub</h1>
  <p class="sub">Everything awaiting review, in one place. Generated {e(stamp)} — re-run the builder to refresh.</p>
  <nav>{nav}</nav>
</header>
<main>{''.join(body)}</main>
<footer>{e(counts)}<br>Source: SnowSnakes public API + Z-Dot R&amp;D artifacts. No client or confidential material.</footer>
</body></html>'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="/tmp/hub")
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)
    doc = build()
    with open(os.path.join(a.outdir, "index.html"), "w") as f:
        f.write(doc)
    print(f"wrote {a.outdir}/index.html ({len(doc)} bytes)")


if __name__ == "__main__":
    main()
