#!/usr/bin/env python3
"""Complete a song in LMMS around a loop generated by the Snow Beats game.

Workflow this implements:
  1. the Snow Beats GAME generates the drum loop (its own preset, its own synth)
  2. the loop is imported into LMMS as an instrument
  3. the song is completed with LMMS's own bundled instrument presets

    scripts/snow_song.py --loop content/experiments/lmms/snow-beats-boombap-92.wav \
        --bpm 92 --out content/experiments/lmms/snow-beats-song.mmp --stems --mp3
"""
from __future__ import annotations
import argparse, os, re, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lmms_beat import Track, afp, run_lmms
from lmms_layer import project_xml
from lmms_presets import find, instrument_from_preset
from lmms_spec import TICKS_PER_BAR, Q, E, S

BAR = TICKS_PER_BAR
ST = 12                     # a 16th note in ticks; patterns are written in steps

# ---- harmony: D natural minor, 2 bars per chord, 8-bar cycle ----------------
CHORDS = {
    "Dm": (38, [50, 53, 57]),
    "Bb": (34, [46, 50, 53]),
    "F":  (41, [53, 57, 60]),
    "C":  (36, [48, 52, 55]),
}
PROGRESSION = ["Dm", "Bb", "F", "C"]     # one chord per 2 bars

# melodic phrases in scale degrees of D minor (1=D), 16 eighth-note slots = 2 bars
DEG = {1: 0, 2: 2, 3: 3, 4: 5, 5: 7, 6: 8, 7: 10, 8: 12}
PHRASES = {
    "Dm": [5, None, 3, 4, None, 3, 2, None, 1, None, 2, 3, None, 5, None, None],
    "Bb": [6, None, 5, 6, None, 8, None, 6, 5, None, 3, 5, None, 4, None, None],
    "F":  [5, None, 7, 8, None, 7, 5, None, 6, None, 5, 4, None, 3, None, None],
    "C":  [6, None, 5, None, 4, 5, 4, None, 2, None, 3, None, 1, None, None, None],
}
LEAD_BASE = 62          # D4

BASS_VERSE = [0, 6, 10]
BASS_FULL = [0, 3, 6, 10, 14]


def build(loop_path, total_bars, bpm, loop_bars=4):
    drums = Track("Drums (Snow Beats)", afp(os.path.abspath(loop_path)), vol=74)
    for b in range(0, total_bars, loop_bars):
        drums.n(b * BAR, 57, 100, loop_bars * BAR)

    bass = Track("Bass (Monstro)", instrument_from_preset(find("Monstro", "Phat")),
                 vol=86, basenote=57)
    pad = Track("Pad (Organic)", instrument_from_preset(find("Organic", "pad_rich")),
                vol=62, pan=14, basenote=57)
    lead = Track("Lead (SID)", instrument_from_preset(find("SID", "Lead")),
                 vol=100, pan=-12, basenote=57)

    for b in range(total_bars):
        bar0 = b * BAR
        chord = PROGRESSION[(b // 2) % len(PROGRESSION)]
        root, voicing = CHORDS[chord]
        stage = b // loop_bars              # one stage per loop repeat

        # --- bass: boombap placement, busier once the arrangement opens up
        slots = BASS_FULL if stage >= 2 else BASS_VERSE
        for i, s in enumerate(slots):
            key = root + (12 if (stage >= 2 and s == 10) else 0)
            bass.n(bar0 + s * ST, key, 96 if i == 0 else 78, 10)
        if b % 4 == 3:
            bass.n(bar0 + 14 * ST, root + 7, 84, 10)   # turn into the next chord

        # --- pad: sustained 2-bar voicings
        if b % 2 == 0:
            for i, key in enumerate(voicing):
                pad.n(bar0, key, 56 - i * 4, 2 * BAR - 10)

        # --- lead: 2-bar phrases, entering at stage 2, lifted an octave at the end
        if stage >= 2:
            phrase = PHRASES[chord]
            oct_up = 12 if stage >= 3 and b >= total_bars - 4 else 0
            for i, d in enumerate(phrase):
                if d is None:
                    continue
                key = LEAD_BASE + DEG[d] + oct_up
                vel = 62 if i % 4 == 0 else 46
                lead.n(bar0 + i * E, key, vel, E - 8)

    return [t for t in (drums, bass, pad, lead) if t.notes]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--loop", required=True)
    ap.add_argument("--bpm", type=int, default=92)
    ap.add_argument("--bars", type=int, default=16)
    ap.add_argument("--out", default="content/experiments/lmms/snow-beats-song.mmp")
    ap.add_argument("--title", default="Snow Beats Session")
    ap.add_argument("--stems", action="store_true")
    ap.add_argument("--mp3", action="store_true")
    a = ap.parse_args()

    tracks = build(a.loop, a.bars, a.bpm)
    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    xml = project_xml(tracks, a.bars, a.bpm, a.title, os.path.basename(a.loop))
    open(a.out, "w").write(xml)
    print(f"wrote {a.out} ({len(xml)} B, {a.bars} bars @ {a.bpm} bpm)")
    for t in tracks:
        print(f"  {t.name:<22} {len(t.notes):>4} notes")

    wav = re.sub(r"\.mmp$", ".wav", a.out)
    run_lmms(["render", a.out, "-o", wav, "-f", "wav", "-s", "44100"])
    print("rendered", wav)
    if a.stems:
        sd = re.sub(r"\.mmp$", "-stems", a.out)
        os.makedirs(sd, exist_ok=True)
        run_lmms(["rendertracks", a.out, "-o", sd, "-f", "wav"])
        print(f"stems -> {sd}/ ({len(os.listdir(sd))})")
    if a.mp3:
        mp3 = re.sub(r"\.mmp$", ".mp3", a.out)
        subprocess.run(["ffmpeg", "-y", "-hide_banner", "-loglevel", "error",
                        "-i", wav, "-b:a", "192k", mp3], check=True)
        print("encoded", mp3)


if __name__ == "__main__":
    main()
